apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
<<<<<<< HEAD
=======
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # aplica ANTES dos ExternalSecrets (wave 0)
>>>>>>> dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets