apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 000-namespace.yaml
  - 005-secret-store.yaml
  - 010-secrets-db.yaml
  - 020-secrets-sqs.yaml
  - 030-auth-service/031-configmap.yaml
  - 030-auth-service/032-secrets.yaml
  - 030-auth-service/033-deployment.yaml
  - 040-flag-service/041-configmap.yaml
  - 040-flag-service/042-deployment.yaml
  - 050-targeting-service/051-configmap.yaml
  - 050-targeting-service/052-deployment.yaml
  - 060-evaluation-service/061-configmap.yaml
  - 060-evaluation-service/062-secrets.yaml
  - 060-evaluation-service/063-deployment.yaml
  - 070-analytics-service/071-configmap.yaml
  - 070-analytics-service/072-deployment.yaml
  - 070-analytics-service/073-scaledobject.yaml